---
abstract: 'Word 2 number conversion in POR.'
author:
  - 'Jose Castro <cog@cpan.org>'
build_requires:
  Test::More: 0
  perl: v5.10.1
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-POR-Words2Nums
requires:
  Perl6::Export::Attrs: 0
  perl: 5.006
  strict: 0
  warnings: 0
version: 0.0577
